
-- Cria豫o do Banco de Dados
CREATE DATABASE AULA_BDI_221;

-- Definir qual banco de dados vamos utilizar
USE AULA_BDI_221;
GO

--CRIA플O DE TABELA
CREATE TABLE PRODUTO(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	DESCRICAO VARCHAR(255),
	TIPO CHAR(1),
	VALOR DECIMAL(5,2),
	CONSTRAINT PK_PRODUTO PRIMARY KEY(ID)
);
GO

TRUNCATE TABLE DBO.PRODUTO
GO
DBCC CHECKIDENT ('DBO.PRODUTO', RESEED, 0);  
GO

--CRIA플O DE TABELA
CREATE TABLE FORMA_PAGAMENTO(
	ID INT IDENTITY(1,1) NOT NULL,
	DESCRICAO VARCHAR(50) NOT NULL,
	CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY(ID)
);
GO

TRUNCATE TABLE DBO.FORMA_PAGAMENTO
GO
DBCC CHECKIDENT ('DBO.FORMA_PAGAMENTO', RESEED, 0);  
GO


--CRIA플O DE TABELA
CREATE TABLE FUNCIONARIO(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	CPF VARCHAR(14) NOT NULL,
	SALARIO DECIMAL(6,2) NOT NULL,
	-- COD ENDERECO
	TIPO CHAR(1) NULL,
	N_CONSELHO INT NULL,
	ESPECIALIDADE VARCHAR(20) NULL,
	COMISSAO DECIMAL(4,2),
	CONSTRAINT PK_FUNCIONARIO PRIMARY KEY(ID)
);
GO


TRUNCATE TABLE DBO.FUNCIONARIO
GO
DBCC CHECKIDENT ('DBO.FUNCIONARIO', RESEED, 0);  
GO


--CRIA플O DE TABELA
CREATE TABLE CLIENTE(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(255) NOT NULL,
	-- COD_ENDERECO
	-- TELEFONE
	EMAIL VARCHAR(50) NOT NULL,
	CONSTRAINT PK_CLIENTE PRIMARY KEY(ID)
);
GO

TRUNCATE TABLE DBO.CLIENTE
GO
DBCC CHECKIDENT ('DBO.CLIENTE', RESEED, 0);  
GO

--CRIA플O DE TABELA
CREATE TABLE PRONTUARIO (
	ID INT IDENTITY(1,1) NOT NULL,
	DESCRICAO VARCHAR(255),
	TEMPERATURA DECIMAL(3,1),
	PESO DECIMAL(3,1),
	CONSTRAINT PK_PRONTUARIO PRIMARY KEY(ID)
);
GO

TRUNCATE TABLE DBO.PRONTUARIO
GO
DBCC CHECKIDENT ('DBO.PRONTUARIO', RESEED, 0);  
GO

--CRIA플O DE TABELA
CREATE TABLE PET(
	ID INT IDENTITY(1,1) NOT NULL,
	NOME VARCHAR(50),
	ESPECIE VARCHAR(50),
	PORTE VARCHAR(50),
	DT_NASC DATE,
	ID_PRONTUARIO INT NULL,
	CONSTRAINT PK_PET PRIMARY KEY(ID),
	CONSTRAINT FK_PET_PRONTUARIO FOREIGN KEY(ID_PRONTUARIO)
	REFERENCES DBO.PRONTUARIO (ID)
);
GO

TRUNCATE TABLE DBO.PET
GO
DBCC CHECKIDENT ('DBO.PET', RESEED, 0);  
GO

--CRIA플O DE TABELA
CREATE TABLE CLIENTE_PET(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_PET INT NOT NULL,
	CONSTRAINT FK_CLIENTE_PET_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID),
	CONSTRAINT FK_CLIENTE_PET_PET FOREIGN KEY (ID_PET)
	REFERENCES DBO.PET (ID),
);
GO

TRUNCATE TABLE DBO.CLIENTE_PET
GO
DBCC CHECKIDENT ('DBO.CLIENTE_PET', RESEED, 0);  
GO

--CRIA플O DE TABELA
CREATE TABLE VENDA(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_FORMA_PAGAMENTO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	ID_FUNCIONARIO INT NOT NULL,
	CONSTRAINT PK_VENDA PRIMARY KEY(ID),
	CONSTRAINT FK_VENDA_FORMA_PAGAMENTO FOREIGN KEY(ID_FORMA_PAGAMENTO)
	REFERENCES DBO.FORMA_PAGAMENTO (ID),
	CONSTRAINT FK_VENDA_CLIENTE FOREIGN KEY (ID_CLIENTE)
	REFERENCES DBO.CLIENTE (ID),
	CONSTRAINT FK_vENDA_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO)
	REFERENCES DBO.FUNCIONARIO (ID)
);
GO

TRUNCATE TABLE DBO.VENDA
GO
DBCC CHECKIDENT ('DBO.VENDA', RESEED, 0);  
GO

--CRIA플O DE TABELA
CREATE TABLE PRODUTO_VENDA(
	ID INT IDENTITY(1,1) NOT NULL,
	ID_PRODUTO INT NOT NULL,
	ID_VENDA INT NOT NULL,
	CONSTRAINT PK_PRODUTO_VENDA PRIMARY KEY(ID, ID_PRODUTO, ID_VENDA),
	CONSTRAINT FK_PRODUTO_VENDA_PRODUTO FOREIGN KEY (ID_PRODUTO)
	REFERENCES DBO.PRODUTO (ID),
	CONSTRAINT FK_PRODUTO_VENDA_VENDA FOREIGN KEY (ID_VENDA)
	REFERENCES DBO.VENDA (ID)
);
GO

TRUNCATE TABLE DBO.PRODUTO_VENDA
GO
DBCC CHECKIDENT ('DBO.PRODUTO_VENDA', RESEED, 0);  
GO